### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Scarysize** [jlfwong/metaballs#1]
Hey, just a quick question:

You are calculating the binary index of your cells here:
https://github.com/jlfwong/metaballs/blob/master/classify-cells.js#L20

Starting with the SW corner of a cell, rotating counter clockwise. Aren't you supposed to start at the NW corner rotating clockwise? Does it even matter?

**Comment by jlfwong** [comment]
As long as all the code you have is consistent about what the classification means, it doesn't matter.

The classification there is consistent with the diagrams presented in http://jamie-wong.com/2014/08/19/metaballs-and-marching-squares/

In the expression

```
      ret[i].push(
        (SW << 0) +
        (SE << 1) +
        (NE << 2) +
        (NW << 3)
      );
```

The least significant bit (the rightmost bit) describes the state of the SW corner, and the most significant bit describes the state of the NE corner.

If you read the resulting bits left to right, the corresponding corners in order are NE, NE, SE, SW.

Hope that helps!
